#
# Screenmirror:
#
# The mode allows the user to mirror the headless output.
# This is primarily used when screencasting to cast only the windows that
# belong to the headless output instead of casting the entire screen.
#
# See the following link for more details:
# https://github.com/emersion/xdg-desktop-portal-wlr/issues/107#issuecomment-1596107337

set $screenmirror /usr/share/sway/scripts/screenmirror.sh
set $start_mirror systemd-cat $screenmirror $headless
set $stop_mirror systemd-cat $screenmirror -k

## Launch // Switch to the workspace for mirroring ##
$bindsym $mod+0 exec $start_mirror, workspace $ws10
## Launch // Switch back from the workspace for mirroring ##
$bindsym $mod+Mod1+0 exec $stop_mirror, workspace back_and_forth
